<?php

namespace App\Controller\back_end;

use App\Form\GuideType;
use App\Entity\Guide;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route ("/admin/guide")
 */
class GuideController extends AbstractController
{
    /**
     * @Route("/affichguideAdmin", name="guide_index_admin")
     */
    public function AfficherGuideAdmin(): Response
    {
        $guide = $this->getDoctrine()->getRepository(guide::class)->findAll();

        return $this->render('back_end/guide/AfficherGuideAdmin.html.twig', [
            'controller_name' => 'GuideController',
            "guide" => $guide,

        ]);
    }

    /**
     * @Route("/ajoutguide", name="guide_new")
     */
    public function new(Request $request): Response
    {
        $guide = new Guide();
        $form = $this->createForm(GuideType::class, $guide);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $file = $form->get('Photo')->getData();
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('guide_directory'),
                $fileName
            );

            // updates the 'brochure' property to store the PDF file name
            // instead of its contents
            $guide->setPhoto($fileName);
            $entityManager->persist($guide);
            $entityManager->flush();
            return $this->redirectToRoute("guide_index_admin");
        }
        return $this->render("back_end/guide/AjoutGuide.html.twig", [
            "form_title" => "Ajouter un guide",
            "form_guide" => $form->createView(),
        ]);
    }

    /**
     * @Route("/deleteGuide/{id}", name="guide_delete")
     */
    public function delete(int $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $guide = $entityManager->getRepository(Guide::class)->find($id);
        $entityManager->remove($guide);
        $entityManager->flush();
        $this->addFlash('success', 'L"action a été effectué');


        return $this->redirectToRoute("guide_index_admin");
    }

    /**
     * @Route("/modifyGuide/{id}", name="guide_edit")
     */
    public function edit(Request $request, int $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();

        $guide = $entityManager->getRepository(Guide::class)->find($id);
        $form = $this->createForm(GuideType::class, $guide);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            // $file stores the uploaded PDF file
            /** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
            //  $file = $guide->getPhoto();
            $file = $form->get('Photo')->getData();
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('guide_directory'),
                $fileName
            );

            // updates the 'brochure' property to store the PDF file name
            // instead of its contents
            $guide->setPhoto($fileName);

            $entityManager->flush();
            $this->addFlash('success', 'L"action a été effectué');
            return $this->redirectToRoute("guide_index_admin");
        }

        return $this->render("back_end/guide/ModifierGuide.html.twig", [
            "form_title" => "Modifier un guide",
            "form_guide" => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName(): string
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
